#!/usr/bin/env python

import argparse
import sys
import requests
from BeautifulSoup import BeautifulSoup
from download_it import download_file

parser = argparse.ArgumentParser(description = 'Searches and downloads subtitle for your movie')
parser.add_argument("movie", type = str,
                    help = "Path to file")
parser.add_argument("language", type = str,
                    help = "Subtitle language")
args = parser.parse_args()

def make_link(movie_name, lang):
    ''' Returns url which contains all subtitles of a particular movie.
    '''
    return 'http://subscene.com/subtitles/%s/%s' %(movie_name, lang)

def search_sub(link):
    ''' Fuction to find all subtitle links.
    '''
    data = requests.get(link)
    soup = BeautifulSoup(data.text)
    del data
    for subs in soup.findAll('td', attrs={'class' : 'a1'}):
        for link in subs.findAll('a'):
            down_link('http://subscene.com' + link.get('href'))

def down_link(link):
    ''' Returns the download link to a particular subtitle.
    '''
    data = requests.get(link)
    soup = BeautifulSoup(data.text)
    del data
    for subs in soup.findAll('div', attrs={'class' : 'download'}):
        for link in subs.findAll('a'):
            user_response = download_file('http://subscene.com' + link.get('href'))
    if 'y' in user_response:
        print "Cool. Enjoy the movie!"
        sys.exit(0)
    else:
        print "Downloading another one. Hang tight!"

if __name__ == '__main__':
    link = make_link(args.movie, args.language)
    search_sub(link)
